
import React from 'react';

interface DashboardFooterProps {
  date?: Date;
}

export const DashboardFooter: React.FC<DashboardFooterProps> = ({ date = new Date() }) => {
  return (
    <div className="text-center text-xs text-muted-foreground pt-4 border-t border-gray-200 dark:border-gray-800">
      <p>Generated by PM Dashboard | {date.toLocaleDateString()} {date.toLocaleTimeString()}</p>
      <p>Confidential - For internal use only</p>
    </div>
  );
};
