// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynylepybxqaqbbzqmrtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlueWxlcHlieHFhcWJienFtcnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDg4NDIsImV4cCI6MjA2MDE4NDg0Mn0._AStJz5hF887R40V0Wn7T0e452CET0KiNu1sTPBD4Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);